---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: mssql-app
  labels:
    db: postgres
    app: mssql_app
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30432    
  selector:
    db: postgres
    app: mssql_app
