---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    name: postgres-data
    type: local
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: postgres-data
  local:
    path: "/postgres_data"
  nodeAffinity:
   required:
     nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8worker-node01
